version: "3.1"
services:
  messaging-service:
    container_name: messaging-service
    image: messaging-service
    build: "./messaging"
    depends_on:
      - messaging-service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://messaging-service-db:5432/messaging-service-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    volumes:
      - ./messaging:/opt/app
    networks:
      - messaging-network

  messaging-service-db:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=messaging-service-db
    image: postgres:latest
    container_name: messaging-service-db
    ports:
      - "7200:5432"
    networks:
      - messaging-network

networks:
  messaging-network:
