spring:
  cloud:
    gateway:
      routes:
        - id: messaging_route
          uri: http://messaging-service:6200
          predicates:
            - Path=/messaging/**,/chat/**,/participant/**
        - id: notification_route
          uri: http://notification-service:6300
          predicates:
            - Path=/notification/**
        - id: user_route
          uri: http://user-service:6100
          predicates:
            - Path=/users/**,/auth/**

logging:
  level:
    root: INFO
    com.chat.gateway.authentication: DEBUG

